src/Teamworks.Web/ViewModels/Mvc/ProfileViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Teamworks.Web.ViewModels.Mvc
{
    public class ProfileViewModel
    {
        public bool IsMyProfile { get; set; }
        public PersonViewModel Person { get; set; }

        public class Input
        {
            [Required(AllowEmptyStrings = false)]
            public string Name { get; set; }
            [Required]
            [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Please enter a valid email address.")]
            public string Email { get; set; }

        }
    }
}

src/Teamworks.Web/Controllers/Mvc/ProfileController.cs
using System.Web.Mvc;
using Raven.Client.Linq;
using Teamworks.Core;
using Teamworks.Core.Authentication;

namespace Teamworks.Web.Controllers.Mvc
{
    public class ProfileController : RavenController
    {
        [HttpGet]
        [ActionName("View")]
        public ActionResult Index(int? identifier)
        {
            ViewBag.Me = true;
            return View(((PersonIdentity) User.Identity).Person);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View("View", ((PersonIdentity)User.Identity).Person);
        }

        [HttpPost]
        public ActionResult Edit(object model)
        {
            return RedirectToAction("Edit");
        }
    }
}

src/Teamworks.Web/Controllers/Mvc/ProfilesController.cs
using System.Web.Mvc;
using AttributeRouting;
using AttributeRouting.Web.Mvc;
using Teamworks.Core;
using Teamworks.Web.Helpers;
using Teamworks.Web.Helpers.AutoMapper;
using Teamworks.Web.Helpers.Extensions.Mvc;
using Teamworks.Web.ViewModels.Mvc;

namespace Teamworks.Web.Controllers.Mvc
{
    [RoutePrefix("profiles")]
    public class ProfilesController : AppController
    {
        [GET("{id?}")]
        public ActionResult Get(int? id)
        {
            var personViewModel = new ProfileViewModel();
            var person = id.HasValue
                             ? DbSession.Load<Person>(id)
                             : DbSession.GetCurrentPerson();

            if (person == null)
                return HttpNotFound();
                
            if (person.Id == DbSession.GetCurrentPersonId())
                personViewModel.IsMyProfile = true;

            personViewModel.Person = person.MapTo<PersonViewModel>();
            return View("View", personViewModel);
        }

        [POST("")]
        public ActionResult Edit(ProfileViewModel.Input model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToRoute("profiles_get");
            }

            var person = DbSession.GetCurrentPerson();
            model.MapPropertiesToInstance(person);

            if (Request.IsAjaxRequest())
            {
                return new JsonNetResult {
                               Data = person.MapTo<PersonViewModel>()
                           };
            }
            return RedirectToRoute("profiles_get");
        }

        [POST("password", RouteName = "profiles_password")]
        public ActionResult ChangePassword(string old, string password, string passwordConfirm)
        {
            var person = DbSession.GetCurrentPerson();
            if (!person.IsThePassword(old))
                ModelState.AddModelError("model.password", "Your old password is wrong");

            if (password != passwordConfirm)
                ModelState.AddModelError("model.password", "Password and confirmation must match");

            if (!ModelState.IsValid)
                return View("View");

            person.ChangePassword(password);
            return RedirectToRoute("View");
        }

    }
}

src/Teamworks.Web/Views/Profiles/Index.cshtml
@using Teamworks.Web.Views
@model Teamworks.Web.ViewModels.Mvc.ProfileViewModel

@{
    ViewBag.Title = @Model.PersonDetails.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    @if (Model.IsMyProfile)
    {
        <a class="btn pull-right" href="#" data-bind="click: function() { editing(true); }, css: { 'hide': editing() }">Edit your profile</a>
        <div class="hide pull-right" data-bind="css: { 'hide': !editing() }">
            <a class="btn btn-mini btn-info" href="#" data-bind="click: update">Save</a>
            <a href="#" data-bind="click: function() { editing(false); }"><i class="icon-remove"></i></a>
        </div>
    }
    <h1>
        <span data-bind="text: name, css: { 'hide': editing() }" >@Model.PersonDetails.Name</span>
        @if (Model.IsMyProfile)
        {
            <input class="hide" type="text" data-bind="value: name, css: { 'hide': !editing() }" />
            <small>This is you</small>
        } 
    </h1>
   
</header>
<div class="row">
    <div class="span3">
        <div>
            <img data-bind="attr: { src: gravatar }" alt="Profile image"/>
        </div>
    </div>
    <div class="span5">
        <h2>Bio</h2>
        <div class="span" data-bind="css: { 'hide': editing() }">
            <h3>Name</h3> 
            <div class="raw"data-bind="text: username">@Model.PersonDetails.Username</div>
            <h3>Email</h3> 
            <div class="raw" data-bind="text: email">@Model.PersonDetails.Email</div>
        </div>
        @if (Model.IsMyProfile)
        {
            <div class="span hide" data-bind="css: { 'hide': !editing() }">
                <form>
                    <h3>Name</h3> 
                    <input type="text" data-bind="value: username"/>
                    <h3>Email</h3> 
                    <input type="text" data-bind="value: email"/>
                </form>
            </div>
        }
    </div>
</div>

<script>
    var viewmodel = function() {
        return tw.pages.ProfileViewModel('/api/people', @Html.ToJson(Model.PersonDetails));
    }
</script>

src/Teamworks.Web/Views/Profiles/View.cshtml
@using Teamworks.Web.Helpers.Extensions
@model Teamworks.Web.ViewModels.Mvc.ProfileViewModel

@{
    ViewBag.Title = @Model.Person.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    <h1>
        @if (@Model.IsMyProfile)
        {
            <a href="#editProfileModal" role="button" data-toggle="modal"><i style="width: auto" class="icon-edit"></i></a>
        }
        <span data-bind="text: name" >@Model.Person.Name</span>
        <small>This is you</small>
    </h1>
</header>
<div class="row">
    <div class="span3">
        <div>
            <img data-bind="attr: { src: gravatar }" alt="Profile image"/>
        </div>
        <br />
    </div>
    <div class="span5">
        <h2>Bio</h2>
        <div class="span" data-bind="css: { 'hide': editing() }">
            <h3>Name</h3> 
            <div class="raw"data-bind="text: username">@Model.Person.Username</div>
            <h3>Email</h3> 
            <div class="raw" data-bind="text: email">@Model.Person.Email</div>
            <br />
            @if (Model.IsMyProfile)
            {
                <a href="#changePasswordModal" role="button" data-toggle="modal">Change password</a>
            }
        </div>
    </div>
</div>
@if (Model.IsMyProfile)
{
    <div id="changePasswordModal" role="button" class="modal hide fade" data-toggle="modal" tabindex="-1">
        <form class="form-horizontal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Change password</h3>
            </div>
            <div class="modal-body">
                <div class="control-group">
                    <label class="control-label" for="inputPassword">Password</label>
                    <div class="controls">
                        <input id="inputPassword" type="password" name="password" placeholder="Password" autofocus="autofocus"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputNewPassword">New password</label>
                    <div class="controls">
                        <input id="inputNewPassword" type="password" name="newPassword" placeholder="New assword"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="inputConfirmPassword">Confirm password</label>
                    <div class="controls">
                        <input id="inputConfirmPassword" type="password" name="confirmPassword" placeholder="Confirm password"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
    </div>
    <div id="editProfileModal" role="dialog" class="modal hide fade">
        <form style="margin: 0" class="form-horizontal" action="@Url.Action("Edit","Profiles")" method="POST">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Edit Profile</h3>
            </div>
            <div class="modal-body">
                <div class="control-group">
                    <label class="control-label" for="name">Name</label>
                    <div class="controls">
                        <input id="inputName" name="name" placeholder="Name" data-bind="value: name" autofocus="autofocus"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="username">Username</label>
                    <div class="controls">
                        <input id="inputUsername" name="username" placeholder="Username" data-bind="value: username"/>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="email">Email</label>
                    <div class="controls">
                        <input id="inputEmail" name="email" placeholder="Email" data-bind="value: email"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary">Save</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>
        </form>
    </div>
}
<script>
    var viewmodel = function() {
        return tw.pages.ProfileViewModel(@Html.ToJson(Model.Person));
    }
</script>